In [1]:
#- 패키지 임포트
import pandas as pd
from tqdm import tqdm
import re
from konlpy.tag import Okt
okt = Okt()
from collections import Counter # 형태소별 빈도 구할 때 사용
from IPython.display import clear_output
from IPython import display # 램효율을 늘리기 위해 아웃풋 display를 지워줄 것.
from ipywidgets import Output

out = Output()
display.display(out)

Output()

In [3]:
''' 파일 불러오기 '''
df = pd.read_csv("../dataset/2022/본문_전처리/나무문화_본문_1월_전처리.csv", encoding='UTF-8')
print(df.shape, df.columns)
corpus = df['split_str'].to_list() # 문장(X문서X)으로 가져와서 실행.
# ↑ 추후에 다른 분석 시도할 때 문장 별 형태소가 필요할 때도 있음. 문장별 형태소와 이를 문서로 합친 게 있으면 편하기 때문에 문장별로 형태소 분석 실행.
print(len(corpus))

(705297, 2) Index(['split_str', 'org_idx'], dtype='object')
705297

In [4]:
''' 형태소 분석 '''
nouns = []
verbs = []
adjs = []
josas = [] # 불용어 목록에 조사 사용하기 위함.
morphs = [] # 품사 태깅 없이 형태소만 추출. 추후 TF-IDF, N-gram등 텍스트 분석은 이 데이터로 진행함.
pos_list = [] # 감성분석할 때 필요.

In [5]:
for i in tqdm(range(len(corpus))):
    # 답변에서 형태소/품사 추출
    try:
        a = okt.pos(corpus[i], norm=True, stem=True) # 단어의 정규화와 어간 추출을 실행(True).
        m = okt.morphs(corpus[i], norm=True, stem=False)
        morphs.append(m) # 형태소 추가
        pos_list.append(a) # 형태소/품사 추가
        for x, y in a:
            # 품사가 명사면 명사 리스트에 단어 추가
            if y == 'Noun':
                nouns.append(x)
            # 품사가 동사면 동사 리스트에 단어 추가
            elif y == 'Verb':
                verbs.append(x)
            # 품사가 형용사면 형용사 리스트에 단어 추가
            elif y == 'Adjective':
                adjs.append(x)
		    # 품사가 조사면 조사 리스트에 단어 추가.
            elif y == 'Josa':
                josas.append(x)
    except:
        pass

100%|██████████| 705297/705297 [9:42:41<00:00, 20.17it/s]

In [ ]:
# 명사, 동사, 형용사 리스트에서 10개 단어씩 출력해서 확인
print(nouns[0:10])
print(verbs[0:10])
print(adjs[0:10])
print(josas[0:10])

In [6]:
''' 명사, 동사, 형용사, 조사 똑같이 아래 코드 반복 '''
# 명사 리스트에서 명사 빈도 리스트 생성
print(len(Counter(nouns))) # 이 값을 밑에 most_common 안에 넣으면 됨.
noun_cnt = Counter(nouns).most_common()

명사 = []
명사빈도 = []
for a, b in noun_cnt:
    명사.append(a)
    명사빈도.append(b)

# 단어와 빈도를 가지고 판다스 데이터프레임(엑셀 표와 비슷) 생성
noun_df = pd.DataFrame({'명사':명사, '명사빈도':명사빈도})
# 명사 데이터프레임을 파일로 저장. .xlsx, .csv, .txt 등 가능.
noun_df.to_csv("../dataset/2022/본문_형태소분석/1월/나무문화_1월_형태소분석(명사).csv", index=False, encoding='UTF-8')
noun_df

140934

         명사    명사빈도
0         것  169780
1         수   94955
2         그   92470
3         이   82276
4        사람   58040
...     ...     ...
140929   이칙       1
140930  송혜진       1
140931   선음       1
140932   쫌생       1
140933  창출레       1

[140934 rows x 2 columns]

In [7]:
''' 명사, 동사, 형용사, 조사 똑같이 아래 코드 반복 '''
# 명사 리스트에서 명사 빈도 리스트 생성
print(len(Counter(verbs))) # 이 값을 밑에 most_common 안에 넣으면 됨.
verb_cnt = Counter(verbs).most_common()

동사 = []
동사빈도 = []
for a, b in verb_cnt:
    동사.append(a)
    동사빈도.append(b)

# 단어와 빈도를 가지고 판다스 데이터프레임(엑셀 표와 비슷) 생성
verb_df = pd.DataFrame({'동사':동사, '동사빈도':동사빈도})
# 명사 데이터프레임을 파일로 저장. .xlsx, .csv, .txt 등 가능.
verb_df.to_csv("../dataset/2022/본문_형태소분석/1월/나무문화_1월_형태소분석(동사).csv", index=False, encoding='UTF-8')
verb_df

1853

         동사    동사빈도
0        하다  694624
1        되다  144188
2        보다   74214
3        않다   67520
4       되어다   61550
...     ...     ...
1848   버정이다       1
1849  찡긋거리다       1
1850  씨근거리다       1
1851  수런거리다       1
1852  허정거리다       1

[1853 rows x 2 columns]

In [8]:
''' 명사, 동사, 형용사, 조사 똑같이 아래 코드 반복 '''
# 명사 리스트에서 명사 빈도 리스트 생성
print(len(Counter(adjs))) # 이 값을 밑에 most_common 안에 넣으면 됨.
adj_cnt = Counter(adjs).most_common()

형용사 = []
형용사빈도 = []
for a, b in adj_cnt:
    형용사.append(a)
    형용사빈도.append(b)

# 단어와 빈도를 가지고 판다스 데이터프레임(엑셀 표와 비슷) 생성
adj_df = pd.DataFrame({'형용사':형용사, '형용사빈도':형용사빈도})
# 명사 데이터프레임을 파일로 저장. .xlsx, .csv, .txt 등 가능.
adj_df.to_csv("../dataset/2022/본문_형태소분석/1월/나무문화_1월_형태소분석(형용사).csv", index=False, encoding='UTF-8')
adj_df

1833

         형용사   형용사빈도
0         있다  311452
1         없다   60603
2         같다   47647
3         좋다   45522
4        아니다   43719
...      ...     ...
1828    다스하다       1
1829    여릿하다       1
1830    몽실하다       1
1831  번드르르하다       1
1832    섬려하다       1

[1833 rows x 2 columns]

In [9]:
''' 명사, 동사, 형용사, 조사 똑같이 아래 코드 반복 '''
# 명사 리스트에서 명사 빈도 리스트 생성
print(len(Counter(josas))) # 이 값을 밑에 most_common 안에 넣으면 됨.
josa_cnt = Counter(josas).most_common()

조사 = []
조사빈도 = []
for a, b in josa_cnt:
    조사.append(a)
    조사빈도.append(b)

# 단어와 빈도를 가지고 판다스 데이터프레임(엑셀 표와 비슷) 생성
josa_df = pd.DataFrame({'조사':조사, '조사빈도':조사빈도})
# 명사 데이터프레임을 파일로 저장. .xlsx, .csv, .txt 등 가능.
josa_df.to_csv("../dataset/2022/본문_형태소분석/1월/나무문화_1월_형태소분석(조사).csv", index=False, encoding='UTF-8')
josa_df

388

        조사    조사빈도
0        을  575984
1        의  471313
2        이  417776
3        에  404215
4        를  275793
..     ...     ...
383   까지만은       1
384  에게서부터       1
385    로구먼       1
386   으로서나       1
387    로구려       1

[388 rows x 2 columns]

In [10]:
df_concat = pd.concat([noun_df,verb_df,adj_df],axis=1)
df_concat.to_csv("../dataset/2022/본문_형태소분석/나무문화_1월_단어종합.txt", index=False, encoding='UTF-8')

In [11]:
df["morphs"] = morphs
df["pos_tag"] = pos_list
df

,split_str,org_idx,morphs,pos_tag
0,방문한지 4달이 조금 안된시점에 포스팅을 하게되었다,0,"[방문, 한지, 4, 달이, 조금, 안된, 시점, 에, 포스팅, 을, 하게, 되었다]","[(방문, Noun), (한지, Noun), (4, Number), (달이, Nou..."
1,사실은 밀려있는 그릿비에게 밀려서 잊고 있었던 코랄라니 카페 공사하는모습은 진작에 ...,0,"[사실, 은, 밀려있는, 그릿비, 에게, 밀려서, 잊고, 있었던, 코랄, 라니, 카...","[(사실, Noun), (은, Josa), (밀리다, Verb), (그릿비, Nou..."
2,대형카페의 규모는 도대체 얼마나 더 커질예정인지 참 가늠이 안되는구나 라는 생각을 ...,0,"[대형, 카페, 의, 규모, 는, 도대체, 얼마나, 더, 커질, 예정, 인지, 참,...","[(대형, Noun), (카페, Noun), (의, Josa), (규모, Noun)..."
3,근래 생긴 기장에 속해있는 카페중에 주차장이 가장 잘되어있다고 생각 수용인원에대한 ...,0,"[근래, 생긴, 기장, 에, 속, 해있는, 카페, 중, 에, 주차장, 이, 가장, ...","[(근래, Noun), (생기다, Verb), (기장, Noun), (에, Josa..."
4,오픈 일자에 방문했는데도 미리 걸려있던 현수막 덕분인지 주차장을 들어가는데 한참을 ...,0,"[오픈, 일자, 에, 방문, 했는데도, 미리, 걸려있던, 현수막, 덕분, 인지, 주...","[(오픈, Noun), (일자, Noun), (에, Josa), (방문, Noun)..."
...,...,...,...,...
705292,일 년 중 한 달을 아주 진하게 찾아오는 우울에 적셔지고 있노라면 blog nave...,13119,"[일, 년, 중, 한, 달, 을, 아주, 진하게, 찾아오는, 우울, 에, 적셔지고,...","[(일, Noun), (년, Noun), (중, Noun), (하다, Verb), ..."
705293,1984 동물농장 을 읽을 때도 느꼈다 옛날 사람이 자신의 시대를 신랄하게 비판한 ...,13119,"[1984, 동물농장, 을, 읽을, 때, 도, 느꼈다, 옛날, 사람, 이, 자신, ...","[(1984, Number), (동물농장, Noun), (을, Josa), (읽다,..."
705294,나는 나 자신이 되면 된다 인간이라면 으레 경험하는 감정을 유순한 마음으로 받아들이...,13119,"[나, 는, 나, 자신, 이, 되면, 된다, 인간, 이, 라면, 으레, 경험, 하는...","[(나, Noun), (는, Josa), (나, Noun), (자신, Noun), ..."
705295,끼야홍 독후감을 좀 더 고심해서 적어야겠어,13119,"[끼, 야홍, 독후감, 을, 좀, 더, 고심, 해서, 적어야겠어]","[(끼, Noun), (야홍, Noun), (독후감, Noun), (을, Josa)..."
705296,2022 01 01 AM2 49,13119,"[2022, 01, 01, AM, 2, 49]","[(2022, Number), (01, Number), (01, Number), (..."

In [12]:
df.to_csv("../dataset/2022/본문_형태소분석/나무문화_본문_1월_형태소분석.txt", index=False, encoding='UTF-8')